name: "Windows CI"
on:
  push:
    branches:
      - master
      - blueprint
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install ninja
        run: |
          choco install ninja
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 6.2.4
          arch: win64_msvc2019_64
          modules: qtmultimedia qtwebsockets qt3d qt5compat
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.10.0
        with:
          sdk: 10.0.22000.0
      - uses: vicr123/libcontemporary/install-libcontemporary@actions
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build project"
        with:
          project: "."
      - uses: vicr123/libcontemporary/deploy-project@actions
        id: deploy
        name: "Deploy project"
        with:
          subdir: "."
      - uses: actions/upload-artifact@v1
        name: Upload Artifact to GitHub Actions
        with:
          name: "squid-airlines-the-game-win"
          path: ${{ steps.deploy.outputs.package }}
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDS }}
          CHANNEL: windows
          ITCH_GAME: squid-airlines-the-game
          ITCH_USER: vicr123
          PACKAGE: ${{ steps.deploy.outputs.package }}
